### ISSUE TITLE
P0: Oddly drawn polygons

### ISSUE THREAD

**Issue by seasmith** [uber/kepler.gl#79]
There are at least three oddly drawn polygons (US counties) in the image below: one in Alaska and two in the contiguous 48 states. This was produced with the kepler.gl website.

![](https://pbs.twimg.com/media/Dej1yk4VAAA5PuV.jpg)

The was geojson file was originally an [sf](https://github.com/r-spatial/sf/) object stored in a .RData file (R language) - subsequently converted to geojson.

I attempted to replicate this problem with the geojson file in D3 v4 ([seen here](https://bl.ocks.org/seasmith/raw/761b1c1f634d27dd4f740df7d87bb591/)), but it did not produce the same oddly drawn polygons.

I have the geojson file, kepler config file, and D3 attempt contained within [this gist](https://gist.github.com/seasmith/761b1c1f634d27dd4f740df7d87bb591).

**Comment by rsimon** [comment]
I'm seeing the same issue, although on a more massive scale :-)

![image](https://user-images.githubusercontent.com/470971/40961366-a933e96c-68a2-11e8-9b55-c8f821fcfd30.png)

I also used the kepler.gl Website. Uploaded the data as a CSV, with a geometry column containing WKT. 

To keep things small, I'm attaching a CSV with a single example (shown below) here: [faroe-islands.csv.zip](https://github.com/uber/kepler.gl/files/2071211/faroe-islands.csv.zip) 

![image](https://user-images.githubusercontent.com/470971/40961079-d3847b24-68a1-11e8-992f-cee6e1c7c141.png)

![image](https://user-images.githubusercontent.com/470971/40961071-cc97f872-68a1-11e8-8853-764792a2a9f2.png)

If it's helpful, I'm happy to share the full CSV. Just let me know!

**Comment by heshan0131** [comment]
This should be fixed once we upgrade to deck.gl v5

**Comment by guidorice** [comment]
@heshan0131 I have noticed this too with some geojson files. Is this because of the polygon winding order, or something else? I tried running https://github.com/mapbox/geojson-rewind to fix a file, but still get the same rendering problem.

btw thanks for confirming a fix is coming in deck.gl 5 👍

**Comment by palamago** [comment]
Indeed. Fixed with latest version of deck.gl. You can close this issue.

**Comment by seasmith** [comment]
Fixed with deck.gl v5.
